services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped

  front:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - back
    restart: unless-stopped
