sonar.projectKey=bastienesquiros_oc_project_7_front
sonar.organization=bastienesquiros
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.exclusions=**/*.spec.ts,node_modules/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/microcrm/lcov.info
